server:
  port: 8787
  servlet:
    context-path: /api


spring:
  application:
    name: permission_demo
  ai:
    openai:
      base-url: https://api.mnzdna.xyz
      api-key: sk-KgvugzpKzki15GFxB72e7782De844b23B3E4Fc6dDf40B29a
      chat:
        options:
          model: gpt-3.5-turbo
    vectorstore:
      pgvector:
        initialize-schema: true
        table-name: vector_store_1536
        remove-existing-vector-store-table: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/know-hub
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day
  allow-list:
    - "/v3/**"
    - "/swagger-ui/**"
    - "/doc.html"
    - "/webjars/**"
    - "/auth/login"
    - "/agent/chat/**"
    - "/favicon.ico"

# MinIO
minio:
  endpoint: http://127.0.0.1:9032/
  access-key: admin
  secret-key: admin123
  bucket-name: permission-demo

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-open-api: true
    enable-group: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: me.pgthinker.controller
